### ISSUE TITLE
请求一份原版sega启动画面和警告

### ISSUE THREAD

**Issue by Frost-Flash** [wjjsn/maimaiDX-TranslateToChinese#2]
非常棒的dx汉化，但是比起魔改的界面还是更喜欢原汁原味的感觉，可以求一份原版的警告和标志吗？

**Comment by wjjsn** [comment]
教程已经放出来了，不是很难，只用修改两个图片就好了，你可以自己试试不行再我来吧，用UABEA就可以了

**Comment by Frost-Flash** [comment]
不用了，谢谢，可以自己弄，才发现readme里面有教程拆包方法，还是感谢啦，汉化真的非常棒

**Comment by Frost-Flash** [comment]
那请问可以问一下这两张图片的名字吗？太多了找不到

**Comment by wjjsn** [comment]
UI_ADV_Img_LogoSEGA-resources.assets-828
UI_ADV_Img_WarningText-resources.assets-389
